name: AD emulator
description: Emulate Active Directory with slapd
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: emulator
        tags: ad_emulator:latest
        load: true
