name: AD emulator
description: Emulate Active Directory with slapd
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: StorFollo-IKT/slapd-ad-emulator

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: emulator
        tags: ad_emulator:latest
        load: true
