on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and export
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: emulator
          tags: ad_emulator:latest
          outputs: type=docker,dest=/tmp/ad_emulator.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ad_emulator
          path: /tmp/ad_emulator.tar

